---
- hosts: app
  gather_facts: true
  become: true
  tasks:
    - name: Install nginx
      apt: pkg=nginx state=present

    - name: Installing npm
      apt: pkg=npm state=present

    - name: download Mongoose
      npm:
        name: mongoose
        global: yes

    - name: Install pm2
      npm:
        name: pm2
        global: yes

    - name: Add ENV variable
      shell: |
        # echo "export DB_HOST=mongodb://192.168.33.11:27017/posts" >> /home/ubuntu/.bashrc
        # source /home/ubuntu/.bashrc
        export DB_HOST="mongodb://192.168.33.11:27017/posts"

    - name: Reverse Proxy
      shell: |
        sudo cp /home/ubuntu/web_config/default /etc/nginx/sites-available/default
        sudo systemctl restart nginx
        sudo systemctl enable nginx

    - name: seed and run app
      shell: |
        cd /home/ubuntu/app/app
        npm install
        node /home/ubuntu/app/app/seeds/seed.js
        pm2 kill
        pm2 start /home/ubuntu/app/app/app.js
